spring:
  datasource:
    url: jdbc:mysql://localhost:3306/msa_step02_order?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

service:
  payment:
    url: http://payment-service/payments

server:
  port: 8080

# cloud config 테스트용 설정 값
custom:
  message: "초기 메시지 - PROD 환경입니다."
  version: "3.0.0"
  
