spring:
  datasource:
    url: jdbc:mysql://localhost:3306/msa_step02_order?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true

service:
  payment:
    url: http://payment-service/payments

server:
  port: 8080
